# version: '2'
# services:
#   mariadb:
#     image: 'mariadb:10'
#     environment:
#       MYSQL_RANDOM_ROOT_PASSWORD: 1
#       MYSQL_DATABASE: moodle
#       MYSQL_USER: moodle
#       MYSQL_PASSWORD: moodlePassword
#     command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed

#     # volumes:
#     #   - $HOME/volumes/mysql:/var/lib/mysql

#   moodle:
#     image: 'bitnami/moodle:3'
#     environment:
#       MOODLE_USERNAME: edu
#       MOODLE_PASSWORD: edu@123
#       MOODLE_EMAIL: admin@edu.org
#       MARIADB_HOST: mariadb
#       MARIADB_PORT_NUMBER: 3306
#       MOODLE_DATABASE_USER: moodle
#       MOODLE_DATABASE_NAME: moodle
#       MOODLE_DATABASE_PASSWORD: moodlePassword
#       ALLOW_EMPTY_PASSWORD: "no"
#       BITNAMI_DEBUG: "true"
#     ports:
#       - '84:80'
#       - '443:443'
#     # volumes:
#     #   - $HOME/volumes/moodle:/bitnami'
#     depends_on:
#       - mariadb

# volumes:
#   mariadb_data:
#     driver: local
#   moodle_data:
#     driver: local



version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:3
    ports:
      - '82:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local